[package]
name = "halley-wl"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["halley-config", "halley-core"]

[dependencies]
smithay = { version = "0.7.0", git = "https://github.com/Smithay/smithay.git", rev = "ff5fa7df392cecfba049ffed55cdaa4e98a8e7ef", default-features = false, features = [
  "backend_winit",
  "backend_egl",
  "renderer_gl",
  "backend_session",
  "backend_session_libseat",
  "backend_drm",
  "backend_gbm",
  "backend_udev",
  "backend_libinput",
  "wayland_frontend",
  "desktop",
] }
smithay-drm-extras = { git = "https://github.com/Smithay/smithay.git", rev = "ff5fa7df392cecfba049ffed55cdaa4e98a8e7ef" }
calloop = "0.14.4"
halley-config = { path = "halley-config" }
rune-cfg = "0.6.1"
xcursor = "0.3"
