[package]
name = "halley"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["halley-cli", "halley-config", "halley-core", "halley-ipc", "halley-portal"]

[dependencies]
smithay = { version = "0.7.0", git = "https://github.com/Smithay/smithay.git", rev = "ff5fa7df392cecfba049ffed55cdaa4e98a8e7ef", default-features = false, features = [
  "backend_winit",
  "backend_egl",
  "renderer_gl",
  "backend_session",
  "backend_session_libseat",
  "backend_drm",
  "backend_gbm",
  "backend_udev",
  "backend_libinput",
  "wayland_frontend",
  "use_system_lib",
  "desktop",
  "xwayland",
] }
smithay-drm-extras = { git = "https://github.com/Smithay/smithay.git", rev = "ff5fa7df392cecfba049ffed55cdaa4e98a8e7ef" }
calloop = "0.14.4"
eventline = "0.9.0"
futures-util = "0.3"
halley-config = { path = "halley-config" }
halley-core = { path = "halley-core" }
halley-ipc = { path = "halley-ipc" }
libc = "0.2"
png = "0.17"
resvg = { version = "0.47", default-features = false }
xcursor = "0.3"
zbus = "5.16"
