[package]
name = "halley-ipc"
version = "0.6.1"
edition = "2024"
description = "Inter-process communication protocol for the Halley Wayland compositor"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
libc = "0.2"
postcard = { version = "1", features = ["use-std"] }
serde = { version = "1", features = ["derive"] }
