[package]
name = "halley-api"
version = "0.3.0"
edition = "2024"
description = "Stable Rust client API for the Halley compositor"
license = "GPL-3.0-only"
readme = "README.md"

[dependencies]
halley-ipc = { version = "0.6.0", path = "../halley-ipc" }
serde = { version = "1", features = ["derive"] }
