[package]
name = "halley-lift"
version = "0.1.0"
edition = "2024"
description = "Search and action launcher for the Halley Wayland compositor"
license = "GPL-3.0-only"
readme = "README.md"

[dependencies]
calloop = "0.14.4"
calloop-wayland-source = "0.4.1"
fontdb = "0.23.0"
freedesktop-icons = "0.4.0"
halley-api = { path = "../halley-api" }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
resvg = { version = "0.47", default-features = false }
rune-cfg = "0.6.1"
rusttype = "0.9.3"
smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.14"

[[bin]]
name = "halley-lift"
path = "src/main.rs"
