[package]
name = "halley-cli"
version = "0.7.0"
edition = "2024"
description = "Command-line interface for interacting with and controlling the Halley Wayland compositor"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "halleyctl"
path = "src/main.rs"

[dependencies]
halley-api = { version = "0.3.0", path = "../halley-api" }
halley-config = { version = "0.7.0", path = "../halley-config" }
serde = "1"
serde_json = "1"
shlex = "1.3"
